import React, { useState } from 'react';
import { Download, Share2, Image as ImageIcon, Loader2 } from 'lucide-react';
import { generateImage } from '../services/geminiService';

export const ImageView: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setIsLoading(true);
    setError(null);
    setImageUrl(null);

    const result = await generateImage(prompt);
    if (result) {
      setImageUrl(result);
    } else {
      setError('Failed to generate image. Please try again.');
    }
    setIsLoading(false);
  };

  const handleDownload = () => {
    if (!imageUrl) return;
    const link = document.createElement('a');
    link.href = imageUrl;
    link.download = 'solo-ai-image.png';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleShare = async () => {
    if (!imageUrl || !navigator.share) {
        alert("Your browser doesn't support the Share API.");
        return;
    }
    try {
        const response = await fetch(imageUrl);
        const blob = await response.blob();
        const file = new File([blob], 'solo-ai-image.png', { type: blob.type });
        await navigator.share({
            title: 'AI Image from Solo AI',
            text: `Generated with prompt: "${prompt}"`,
            files: [file],
        });
    } catch (err) {
        console.error('Share failed:', err);
    }
  };

  return (
    <div className="h-full flex flex-col p-4 space-y-4">
      <h1 className="text-2xl font-bold bg-gradient-to-r from-brand-blue to-brand-purple text-transparent bg-clip-text text-center pt-4">Image Generator</h1>
      
      <div className="flex-1 flex flex-col items-center justify-center space-y-6">
        <div className="w-full max-w-lg p-2 bg-dark-card rounded-xl border border-dark-accent shadow-lg">
          {imageUrl ? (
            <img src={imageUrl} alt="Generated by AI" className="rounded-lg w-full aspect-square object-cover" />
          ) : (
            <div className="w-full aspect-square bg-dark-accent/50 rounded-lg flex flex-col items-center justify-center text-gray-500">
              {isLoading ? (
                  <>
                    <Loader2 size={48} className="animate-spin text-brand-blue mb-4" />
                    <p>Generating your masterpiece...</p>
                  </>
              ) : (
                  <>
                    <ImageIcon size={48} className="mb-4" />
                    <p>Your generated image will appear here</p>
                  </>
              )}
            </div>
          )}
        </div>

        {error && <p className="text-red-500 text-center">{error}</p>}
        
        {imageUrl && (
          <div className="flex items-center gap-4">
            <button onClick={handleDownload} className="flex items-center gap-2 px-4 py-2 bg-dark-accent text-white rounded-lg hover:bg-brand-blue transition-colors">
              <Download size={18} /> Download
            </button>
            {navigator.share && (
                <button onClick={handleShare} className="flex items-center gap-2 px-4 py-2 bg-dark-accent text-white rounded-lg hover:bg-brand-purple transition-colors">
                  <Share2 size={18} /> Share
                </button>
            )}
          </div>
        )}
      </div>

      <div className="fixed bottom-24 left-0 right-0 px-4 z-20">
        <div className="bg-dark-card/80 backdrop-blur-sm p-3 rounded-xl flex items-center gap-3 border border-dark-accent max-w-lg mx-auto">
          <input
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Describe the image..."
            className="flex-1 bg-transparent focus:outline-none placeholder-gray-500"
            disabled={isLoading}
            onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
          />
          <button onClick={handleGenerate} disabled={isLoading || !prompt.trim()} className="bg-brand-purple px-5 py-2 rounded-lg text-white font-semibold disabled:opacity-50 disabled:cursor-not-allowed hover:shadow-glow-purple transition-shadow">
            {isLoading ? <Loader2 className="animate-spin"/> : 'Generate'}
          </button>
        </div>
      </div>
    </div>
  );
};
